background = #f5f5f7
foreground = #1d1d1f
cursor-color = #000000
selection-background = #b3d7ff
selection-foreground = #000000

palette = 0=#f5f5f7
palette = 1=#d70015
palette = 2=#248a3d
palette = 3=#a05a00
palette = 4=#0040dd
palette = 5=#8944ab
palette = 6=#0071a4
palette = 7=#1d1d1f
palette = 8=#8e8e93
palette = 9=#ff3b30
palette = 10=#34c759
palette = 11=#b25000
palette = 12=#007aff
palette = 13=#af52de
palette = 14=#008299
palette = 15=#000000

background-opacity = 0.78
background-blur = true
