foreground #1d1d1f
background #f5f5f7
selection_foreground #000000
selection_background #b3d7ff

cursor #000000
cursor_text_color #f5f5f7

active_border_color #007aff
active_tab_background #007aff

color0 #f5f5f7
color1 #d70015
color2 #248a3d
color3 #a05a00
color4 #0040dd
color5 #8944ab
color6 #0071a4
color7 #1d1d1f
color8 #8e8e93
color9 #ff3b30
color10 #34c759
color11 #b25000
color12 #007aff
color13 #af52de
color14 #008299
color15 #000000

background_opacity 0.78
dynamic_background_opacity yes
